#!/bin/bash
set -e
echo TESTING WITH "$@" ---------------------------------------------
set -x
ledger --market -f "$@" --limit "has_tag('ending')" --format "%(format_date(tag('ending'), '%Y-%m-%d')) %(account) %(payee)\n" reg
